name: k6 Performance Test
on: [push, pull_request]
jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ensure results directory exists
        run: mkdir -p results
      - name: Run k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: blazedemo_test.js
          args: --out json=results/results.json
        continue-on-error: true
      - name: Upload JSON result
        uses: actions/upload-artifact@v4
        with:
          name: k6-results-json
          path: results/results.json
      - name: Generate HTML report
        run: npx k6-reports results/results.json -o results/results.html
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: k6-results-html
          path: results/results.html