name: k6 Performance Test
on: [push, pull_request]

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ensure results directory exists
        run: mkdir -p results

      - name: Run k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: blazedemo_test.js
        continue-on-error: true

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: k6-results-html
          path: results/results.html
